stepper_config:
  num_joints: 11
  num_grip_joints: 4
  joint_names:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
    - gripper_joint_1
    - gripper_joint_2
    - gripper_joint_3
    - gripper_joint_4
  deg_per_step: # this actually needs to be rad per step
  # current values are estimates
    - 0.6 #0.09    # 360 / 4000
    - 0.05 #0.018   # 5000 / 90
    - 0.3 #0.036   # 90 / 2500
    - 0.05 #0.3     # 90 / 300
    - 0.3 #0.3     # 90 / 300
    - 0.3
    - 0.3

  rad_per_enc_step:
    - 0.000532
    - 0.0000436
    - 0.000873
    - 0.000873 #0.000145
    - 0.000873
    - 0.000873
    - 0.000262

  enc_steps_per_rad: # steps per radian
    - 1909.9 # (4000 * 6) / (2pi) is enc_steps per radian
    - 22918.3 # (4000)
    - 1146.9 # (300 * 4 * 6) / (2pi) is enc_steps per radian
    - 6875.5
    - 1146.9
    - 1146.9
    - 3819.7 # (4000 * 6) / (2pi) is enc_steps per radian


  gripper_gain: 50
  gains:
    joint_1: {p: 60,  d: 0, i: 0.01, i_clamp: 1}
    joint_2: {p: 65,  d: 0, i: 0.1, i_clamp: 1}
    joint_3: {p: 40,  d: 0, i: 0.1, i_clamp: 1} # Good!
    joint_4: {p: 65,  d: 0, i: 0.01, i_clamp: 1}
    joint_5: {p: 40,  d: 0, i: 0.001, i_clamp: 1} # Good!
    joint_6: {p: 60, d: 0.1, i: 0.05, i_clamp: 1}
    joint_7: {p: 45, d: 0.1, i: 0.01, i_clamp: 1}
  goal_position_accuracy: 0.1
  max_goal_time: 10 # in seconds