pose:
  post_throw:
    position:
      x: -0.003
      y: 0.23
      z: 0.132
    orientation:
      x: 0.0215694
      y: 0.702411
      z: 0.00727993
      w: 0.711407


joints:

# test poses:
  home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  test:
    - 2
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  test2:
    - -2
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  
  pre_pickup:
    - 0.663
    - -0.11
    - -0.419
    - 0
    - 0.45
    - 0

  pickup:
    - 0.68
    - 0
    - -0.125
    - 0.017
    - 0.017
    - 0

# unfolding stages starting from inital position during flight 
  folding:
    pos_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_3:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_4:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_5:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_6:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_7:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_8:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

# pickup object 1 poses
  pickup_obj_1:
    pos_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

      # continue with the poses to pickup the first ball...

# pickup object 2 positions
  pickup_obj_2:
    pos_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

      # continue with the poses to picup the second ball...

# positions for picking up the cube
  pickup_obj_3:
    pos_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

      # continue with the poses to picup the first cube...

# throw object 2 movements
  throw_obj_1:
    pos_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

# throw object 2 movments 
  throw_obj_2:
    pos_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

# throw object 3 positions
  throw_obj_3:
    pos_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

# poses to yeet the objects
  discard_obj:
    pos_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pos_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0




grip_pose:
  open: 1
  close: -0.1
  half_close: 0.5

